networks:
  staybook-net:

volumes:
  kafka-data:
  mongo-volume:
  postgres-volume:
  event-store-logs:
  event-store-data:

services:
  modules_user:
    build: .docker/node
    deploy:
      replicas: 1
    working_dir: "/usr/src/app"
    volumes:
      - "./Kalat/StayBook/Modules/UserManagement:/usr/src/app"
    command: sh -c "pnpm start:dev"
    networks:
      staybook-net:
        aliases:
          - modules.user
    depends_on:
      - system_broker
      - system_postgres
      - system_schema_registry
    env_file:
      - path: ./Kalat/StayBook/Modules/UserManagement/.env.default
        required: true
      - path: ./Kalat/StayBook/Modules/UserManagement/.env
        required: false

  system_gateway:
    build: .docker/node
    deploy:
      replicas: 1
    volumes:
      - "./Kalat/StayBook/System/Gateway:/usr/src/app"
    working_dir: "/usr/src/app"
    command: sh -c "pnpm install --frozen-lockfile && pnpm start:dev"
    networks:
      staybook-net:
        aliases:
          - system.gateway
    depends_on:
      - system_broker
      - system_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.system_gateway.loadbalancer.server.port=3000"
      - "traefik.http.routers.system_gateway.rule=Host(`gateway.staybook.localhost`)"
      - "traefik.http.routers.system_gateway.entrypoints=web"
    env_file:
      - path: ./Kalat/StayBook/System/Gateway/.env
        required: false

  system_schema_registry:
    image: confluentinc/cp-schema-registry:7.6.0
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: system.broker:9092
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: "_schemas"
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_CREATE_NUM_PARTITIONS: 1
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_CREATION_ENABLE: "true"
    networks:
      staybook-net:
        aliases:
          - system.schema-registry
    depends_on:
      - system_proxy
      - system_broker
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.system_schema_registry.loadbalancer.server.port=8081"
      - "traefik.http.routers.system_schema_registry.rule=Host(`schema-registry.staybook.localhost`)"
      - "traefik.http.routers.system_schema_registry.entrypoints=web"

  system_schema_build:
    build: .docker/node
    networks:
      staybook-net:
        aliases:
          - system.schema-build
    command: sh -c "pnpm install --frozen-lockfile && pnpm run register"
    working_dir: "/usr/src/app"
    volumes:
      - "./Kalat/StayBook/System/Contracts:/usr/src/app"
    environment:
      REGISTRY_URL: http://system.schema-registry:8081
    depends_on:
      - system_broker
      - system_schema_registry

  system_event_store:
    image: docker.kurrent.io/kurrent-latest/kurrentdb:latest
    environment:
      - KURRENTDB_CLUSTER_SIZE=1
      - KURRENTDB_INSECURE=true
      - KURRENTDB_RUN_PROJECTIONS=All
      - KURRENTDB_START_STANDARD_PROJECTIONS=true
      - KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP=true
      - KURRENTDB_NODE_PORT=2113
    networks:
      staybook-net:
        aliases:
          - system.event-store
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.system_event_store.loadbalancer.server.port=2113"
      - "traefik.http.routers.system_event_store.rule=Host(`event-store.staybook.localhost`)"
      - "traefik.http.routers.system_event_store.entrypoints=web"
    volumes:
      - event-store-data:/var/lib/kurrentdb
      - event-store-logs:/var/log/kurrentdb

  system_proxy:
    image: traefik:latest
    networks:
      staybook-net:
        aliases:
          - kmotion-traefik
    ports:
      - "80:80"
    volumes:
      - ./.docker/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.system_proxy.rule=Host(`traefik.staybook.localhost`)"
      - "traefik.http.routers.system_proxy.entrypoints=web"
      - "traefik.http.routers.system_proxy.service=api@internal"

  system_broker:
    image: apache/kafka:4.1.1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      staybook-net:
        aliases:
          - system.broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://system.broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@system.broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  system_kafka_ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      staybook-net:
        aliases:
          - system.kafka_ui
    environment:
      KAFKA_CLUSTERS_0_NAME: staybook_broker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: system_broker:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      SERVER_SERVLET_CONTEXT_PATH: /
    depends_on:
      - system_broker
      - system_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.system_kafka_ui.loadbalancer.server.port=8080"
      - "traefik.http.routers.system_kafka_ui.rule=Host(`kafka.staybook.localhost`)"
      - "traefik.http.routers.system_kafka_ui.entrypoints=web"

  system_postgres:
    image: postgres:17.6
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      staybook-net:
        aliases:
          - system.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./.docker/postgres:/docker-entrypoint-initdb.d

  system_http_client:
    image: jetbrains/intellij-http-client
    command: request.http
    volumes:
      - ./request.http:/request.http
    working_dir: /
    networks:
      staybook-net:

